# Gitignore creator
gi() {
  curl -sL "https://www.gitignore.io/api/$@"
}

# Container upgrade via watchtower
watchtower() {
  if [ ! -f "$HOME/.docker/config.json" ]; then
    mkdir -p "$HOME/.docker"
    touch "$HOME/.docker/config.json"
    echo '{}' >> "$HOME/.docker/config.json"
  fi
  docker pull docker.io/containrrr/watchtower:latest
  docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v "$HOME/.docker/config.json":/config.json:ro docker.io/containrrr/watchtower:latest --run-once
}
