---
# Based on https://lgug2z.com/articles/building-and-privately-caching-x86-and-aarch64-nixos-systems-on-github-actions/
# Went through many revisions to land on what's here today
name: "build-nixos"
on:
  workflow_dispatch:
  push:
    branches:
      - dev
    # Only run if nix files, the lockfile, or secrets change
    paths:
      - "**.nix"
      - "flake.lock"
      - "**.yml"
      # On the one hand I never use yaml over yml
      # On the other I'd hate to leave them out of this in the event I do need it
      - "**.yaml"
env:
  # nix-fast-build common args
  # Reduced workers and skipping cached to help with attic uploads
  # Also moved Attic to it's own bespoke config
  buildArgs: "--no-nom -j 2 --eval-workers 2"
jobs:
  build:
    runs-on: TimeDial-ubuntu-latest
    steps:
      - name: Checkout Code
        uses: https://github.com/actions/checkout@v6
      - name: Run Prereqs
        uses: ./.forgejo/workflows-composite/setup-nix
        with:
          ssh_key: ${{ secrets.PRIVATE_FLAKE_SSH_KEY }}
          attic_token: ${{ secrets.ATTIC_TOKEN }}
          github_token: ${{ secrets.PAT_GITHUB }}
      - name: Build Packages from Flake
        uses: https://github.com/nick-fields/retry@v4
        with: 
          timeout_minutes: 15
          max_attempts: 3
          command: |
            nix-fast-build ${buildArgs} --flake ./#packages
      - name: Upload Packages to Attic and cleanup
        uses: https://github.com/nick-fields/retry@v4
        with: 
          timeout_minutes: 30
          max_attempts: 3
          command: |
            attic push zelec-nixos-config ./result*
            just cleanup
      - name: Build NixOS Host Configs from Flake
        uses: https://github.com/nick-fields/retry@v4
        with: 
          timeout_minutes: 30
          max_attempts: 3
          command: |
            nix-fast-build ${buildArgs} --flake ./#nixosConfigurations --select 'configs: builtins.mapAttrs (name: value: value.config.system.build.toplevel) configs'
      - name: Upload NixOS Host Configs to Attic and cleanup
        uses: https://github.com/nick-fields/retry@v4
        with: 
          timeout_minutes: 15
          max_attempts: 3
          command: |
            attic push zelec-nixos-config ./result*
            just cleanup